create table students
(
    id     bigint generated by default as identity not null ,
    fullname   text  not null,
    birthdate  timestamp(6) without time zone not null,
    created timestamp(6) without time zone not null,
    updated   timestamp(6) without time zone not null,
    constraint pk_stud primary key (id)
);

create function trigger_set_timestamps_for_updated_entry() returns trigger
    language plpgsql
as
$$
begin
    new.created = old.created;
    new.updated = now();
    return new;
end;
$$;

create function trigger_set_timestamps_for_new_entry() returns trigger
    language plpgsql
as
$$
declare
    now_timestamp timestamp := now();
begin
    new.created = now_timestamp;
    new.updated = now_timestamp;
    return new;
end;
$$;

create trigger set_timestamp_update
    before update
    on students
    for each row
execute procedure trigger_set_timestamps_for_updated_entry();

create trigger set_timestamp_insert
    before insert
    on students
    for each row
execute procedure trigger_set_timestamps_for_new_entry();