create table students
(
    id     bigint generated by default as identity not null ,
    fullname   text  not null,
    birthdate  timestamp(6) without time zone not null,
    created timestamp(6) without time zone not null,
    updated   timestamp(6) without time zone not null,
    constraint pk_stud primary key (id)
);