create table student_grades
(
    id bigint generated by default as identity not null,
    student_id int references students(id),
    grade_id   int references grades(id),
    created  timestamp without time zone not null,
    updated  timestamp without time zone not null,
    constraint pk_stud_grade primary key (id)
);

create trigger set_timestamp_update
    before update
    on student_grades
    for each row
execute procedure trigger_set_timestamps_for_updated_entry();

create trigger set_timestamp_insert
    before insert
    on student_grades
    for each row
execute procedure trigger_set_timestamps_for_new_entry();