create table student_grades
(
    id bigint generated by default as identity not null,
    student_id int references students(id),
    grade_id   int references grades(id),
    created  timestamp without time zone not null,
    updated  timestamp without time zone not null,
    constraint pk_stud_grade primary key (id)
);
