INSERT INTO grades (id, text, created, updated)
VALUES (2, 'неуд', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (3, 'уд', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (4, 'хор', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 'отл', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
